### PR TITLE
Add AUTHORS.md

### PR DESCRIPTION
**Pull request by jankrepl**

### CODE REVIEW

**Review by FrancescoCasalegno — COMMENTED** [review]
Hi Honza, thanks for taking care of this!

A few small notes (that may not be on Confluence yet since they were discussed yesterday).
- [x] Section "Contributors" can be eliminated (the difference wrt to "Authors" is not even entirely clear).
- [ ] I saw Alex showing examples of people lists in the format of bullet lists rather than comma-separated elements, maybe we can do it with that style so it's also easier to visualize changes?
- [x] Please also add Emilie to the list

**Comment by jankrepl** [comment]
> I saw Alex showing examples of people lists in the format of bullet lists rather than comma-separated elements, maybe we can do it with that style so it's also easier to visualize changes?
I was following reading [this](https://bbpteam.epfl.ch/project/spaces/display/BBPSTD/Repository+Requirements#RepositoryRequirements-AUTHORS) and it seems like it should be comma separated. However, feel free to decide which convention we are going to use.

> Section "Contributors" can be eliminated (the difference wrt to "Authors" is not even entirely clear).
Good point. Will do that!

> Please also add Emilie to the list
Definitely will do that!

**Comment by FrancescoCasalegno** [comment]
Hi @jankrepl ,

I just talked to Alex who said he will update the comma-separated list into a bullet-list.

So we can go with a bullet-list and then 👍  from my side!

**Review by FrancescoCasalegno — APPROVED** [review]

**Comment by jankrepl** [comment]
There seems to be some problem with the CI. I can investigate later.

**Pull request merged**
